install.packages('dplyr')
(rollno=1:30)
(sname=paste('student',1:30,sep=" "))
(gender=sample(c('M',"F")))
set.seed(1234)#to replicate the same pattern
(gender=sample(c('M','F'), size=30, replace=T))
table(gender)
(gender=sample(c('M','F'), size=30, replace=T, prob=c(.7,.3)))
(marks1=floor(rnorm(30,mean=50,sd=10)))
(marks2=ceiling(rnorm(30,40,5)))
(course= sample(c('bba','mba'), size=30, replace=T, prob=c(.5,.5)))
rollno; sname; course
df1= data.frame(rollno, sname, gender, marks1, marks2, course, stringsAsFactors = F)
df1$gender= factor(df1$gender)
df1$gender= factor(df1$course)
library(dplyr)
df1
df1 %>% group_by(gender) %>% summarise(meanM1= mean(marks1), meanM2=mean(marks2)
summarise(mtcars, avg = mean(mpg))
summarise(df1, meanM1 = mean(marks1))
mean(mtcars$mpg)
names(mtcars)
table(mtcars$am)
table(mtcars$cyl)
table(mtcars$gear)
table(mtcars$carb)
table(mtcars$cyl, mtcars$am)
table(mtcars$cyl, mtcars$am, mtcars$vs)
xtabs(~cyl+am+vs, data=mtcars)
mtcars %>% group_by(cyl) %>% summarise(mean(mpg))
mtcars %>% group_by(gear,cyl) %>% summarise(meanMPG=mean(mpg)) %>% arrange(meanMPG)
arrange(desc(meanMPG))

mtcars%>% select(mpg,wt) %>% head(n=7)
mtcars %>% select(mpg,wt) %>% slice(c(1,5,6))
seq(1,32,2)                                    
mtcars %>% select(mpg,wt) %>% slice(seq(1,32,2)) #alternate rows
mtcars %>% filter(mpg>25) %>% select(mpg,wt,hp,am)
mtcars %>% filter(mpg>25 & hp<60) %>% select(mpg,wt,hp,am)

mtcars %>% sample_n(3)
mtcars %>% sample_frac(.3)
